### ISSUE TITLE
First release 0.0.1

### ISSUE THREAD

**Issue by fengmk2** [fengmk2/fawave_desktop#5]
Try and tell me the bugs.

Thanks.
## 0.0.1
- nw: [FaWave.nw](http://nfs.nodeblog.org/fawave/desktop/0.0.1/FaWave.nw)
- Mac: [FaWave.app](http://nfs.nodeblog.org/fawave/desktop/0.0.1/FaWave_mac.zip)
- Linux: [FaWave_linux_x32](http://nfs.nodeblog.org/fawave/desktop/0.0.1/FaWave_linux_x32.zip) | [FaWave_linux_x64](http://nfs.nodeblog.org/fawave/desktop/0.0.1/FaWave_linux_x64.zip)
- Window: [FaWave_win32.exe](http://nfs.nodeblog.org/fawave/desktop/0.0.1/FaWave_win32.zip)

**Comment by QLeelulu** [comment]
FaWave.app 打不开，提示损坏了

**Comment by fengmk2** [comment]
不会吧。。。现在还是？

**Comment by QLeelulu** [comment]
可以了

**Comment by fengmk2** [comment]
good!!!! 第一次打包的有问题。

**Comment by fengmk2** [comment]
window版本的也试试。

**Comment by QLeelulu** [comment]
是不用装NODE环境的吧？？ 我机器上都有node环境的

**Comment by fengmk2** [comment]
## 不需要的，node已经在nw.pkg带进去了。

MK2, FaWave, Net4Team ☺nodejs
TEL: 18668079069
Github: https://github.com/fengmk2
微博: @Python发烧友
Twitter: @fengmk2
CNode: http://cnodejs.org/user/suqian
Blog: http://fengmk2.github.com/

**Comment by fengmk2** [comment]
哈哈，晚上注册个开发者账号，发布一下。

**Comment by QLeelulu** [comment]
win7下没问题

**Comment by QLeelulu** [comment]
win7下没问题

**Comment by fengmk2** [comment]
你按一下键盘 m

**Comment by fengmk2** [comment]
good!!! node-webkit靠谱。

**Comment by QLeelulu** [comment]
呃，不要急着发布吧。

**Comment by fengmk2** [comment]
哈哈，主要是看看能否通过审核，如果不行。。。就白干了。

**Comment by rockdai** [comment]
winxp 也OK~

**Comment by fengmk2** [comment]
@rockdai good

**Comment by samma835** [comment]
win7表示无问题～赞一个！

**Comment by fengmk2** [comment]
打开url有问题

Sent from my iPhone

On 2012-10-7, at 17:00, bullda notifications@github.com wrote:

win7表示无问题～赞一个！

—
Reply to this email directly or view it on
GitHubhttps://github.com/fengmk2/fawave_desktop/issues/5#issuecomment-9206353.

**Comment by JokerQyou** [comment]
Linux 64位不行。窗口出不来，终端跑有提示到inited.。

**Comment by zsxsoft** [comment]
Win8 Downloading

**Comment by samma835** [comment]
嗯，果然，闪现一个console，然后停在一个console里。

On Sun, Oct 7, 2012 at 5:06 PM, fengmk2 notifications@github.com wrote:

> 打开url有问题
> 
> Sent from my iPhone
> 
> On 2012-10-7, at 17:00, bullda notifications@github.com wrote:
> 
> win7表示无问题～赞一个！
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/fengmk2/fawave_desktop/issues/5#issuecomment-9206353>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fengmk2/fawave_desktop/issues/5#issuecomment-9206401.

## 

Ma Shanhu MaShanHu@Gmail.com

**Comment by vae-1989** [comment]
桌面版 win7下毫无压力~~要是能把已经看过的 @我 和 @评 已经评论微博不再重新提示就好了~这样就不用再chrome的插件和桌面版两边看一样的内容了~~ 谢谢你的作品 真的很好~

**Comment by fengmk2** [comment]
本周末会进行一次0.1.0发布，到时候会将一些细节完善好。

---

MK2, FaWave, Net4Team ☺nodejs
TEL: 18668079069
Github: https://github.com/fengmk2
微博: @Python发烧友
Twitter: @fengmk2
CNode: http://cnodejs.org/user/suqian
Blog: http://fengmk2.github.com/

**Comment by samma835** [comment]
今天发现chrome版的支持多平台+新浪同步了，记得新浪不是不参与同步的吗。。

2012/10/8 fengmk2 notifications@github.com

> 本周末会进行一次0.1.0发布，到时候会将一些细节完善好。
> 
> ---
> 
> MK2, FaWave, Net4Team ☺nodejs
> TEL: 18668079069
> Github: https://github.com/fengmk2
> 微博: @Python发烧友
> Twitter: @fengmk2
> CNode: http://cnodejs.org/user/suqian
> Blog: http://fengmk2.github.com/
> 
> On Oct 8, 2012, at 9:53 AM, vae-1989 notifications@github.com wrote:
> 
> > 桌面版 win7下毫无压力要是能把已经看过的 @我 和 @评
> > 已经评论微博不再重新提示就好了~这样就不用再chrome的插件和桌面版两边看一样的内容了 谢谢你的作品 真的很好~
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fengmk2/fawave_desktop/issues/5#issuecomment-9218223.

## 

Ma Shanhu MaShanHu@Gmail.com

**Comment by fengmk2** [comment]
@bullda 低调。。。

**Comment by vae-1989** [comment]
期待中~~

**Comment by samma835** [comment]
ÊÕµ½¡£¡£

On Mon, Oct 8, 2012 at 3:49 PM, fengmk2 notifications@github.com wrote:

> @bullda https://github.com/bullda µÍµ÷¡£¡£¡£
> 
> ¡ª
> Reply to this email directly or view it on GitHubhttps://github.com/fengmk2/fawave_desktop/issues/5#issuecomment-9218533.

## 

Ma Shanhu MaShanHu@Gmail.com

**Comment by samma835** [comment]
直接回复Gmail为什么乱码了，damn it..

**Comment by hillwah** [comment]
win7 64下，右键新窗口打开连接或图片弹命令行，不能在浏览器或者新的NW打开。还有，我这里添加腾讯的微博，授权直接404不知道是不是这里的问题。
